disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - missing_docs

included:
  - Calculator_SwiftUI

excluded:
  - Pods
  - .build

line_length: 120
type_body_length: 300
file_length: 500

reporter: "xcode"
